salesforce:
  password: "![FL8gabAzbGxMZNpZOYcfoQ==]"
  username: "vignesh.br@apisero.com"
  token: "![2xcwrMqzTcQw2YCky7bGyoRvaN9fR8Sgi6IhR5ACppY=]"
  
http:
  port: "8083"
  host: "localhost"
  
ftp:
  host: "localhost"
  port: "21"
  username: "usecase"
  password: "![CVn9wxhqr5A=]"